
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: static/**  #指定对应的目录
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true